[package]
name = "chapter_1_2"
version = "0.1.0"
edition.workspace = true
description = "Clasp derive Tutorial"
authors = ["Your Name"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace =  true }
