[package]
name = "rust-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
serde_json = "1.0.108"
structopt = "0.3.26"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1.0"
