
[workspace]
resolver = "2"
members = [
    "chapter_0","chapter_1", "chapter_1_2"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
clap = { version = "4.4.11", features = ["derive"] }
